<?php
/**
 * Title: Plan Dekton - Surface Intelligence
 * Slug: plan-dekton/section-surface-intelligence
 * Categories: plan-dekton
 */
?>
<!-- wp:group {"tagName":"section","className":"surface-intelligence pds-section","layout":{"type":"constrained"},"metadata":{"name":"Surface Intelligence"}} -->
<section class="wp-block-group surface-intelligence pds-section" id="surface-intelligence"><!-- wp:group {"className":"section-heading reveal","layout":{"type":"constrained"}} --><div class="wp-block-group section-heading reveal"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Surface Intelligence</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Une surface pensee pour les espaces exigeants.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Dekton permet de concevoir un plan esthetique et technique : dimensions, decoupes, chants, credence et integration de l'evier doivent etre anticipes des le brief.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:columns {"className":"tech-grid"} --><div class="wp-block-columns tech-grid"><!-- wp:column {"className":"tech-card reveal"} --><div class="wp-block-column tech-card reveal"><!-- wp:heading {"level":3} --><h3>Chaleur</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Une surface pensee pour les casseroles, plaques chaudes et usages intensifs du quotidien.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"tech-card reveal"} --><div class="wp-block-column tech-card reveal"><!-- wp:heading {"level":3} --><h3>Rayures</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Une matiere adaptee aux plans sollicites, avec les bons gestes de coupe.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"tech-card reveal"} --><div class="wp-block-column tech-card reveal"><!-- wp:heading {"level":3} --><h3>Taches</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Un entretien simple avec une eponge douce, de l'eau chaude et un produit adapte.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></section>
<!-- /wp:group -->